// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

const databaseUrl = (globalThis as {
  process?: { env?: Record<string, string | undefined> };
}).process?.env?.["DATABASE_URL"];

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
};
